name: Build

on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]

jobs:

  build:

    name: Build

    runs-on: ubuntu-latest

    steps:

    - name: Checkout
      uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4
      with:
        fetch-depth: 0

    - name: Download .NET SDKs
      uses: actions/setup-dotnet@67a3573c9a986a3f9c594539f4ab511d57bb3ce9 # v4
      with:
        dotnet-version: |
          8.0
          9.0
          10.0

    - name: Test
      run: dotnet test Glyph3.slnx --configuration Release
